name: validate
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gnu:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Prepare the environment
        run: |
          sudo apt-get install libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev
          mkdir librestore_gnu_package
          mkdir librestore_gnu_install
          mkdir librestore_gnu_userconfig

      - name: Compile
        run: ./.librestore/gnu.sh librestore_gnu_package

      - name: Test install
        run: ./librestore_gnu_package/install.sh ../librestore_gnu_install

      - name: Test run
        run: ./librestore_gnu_install/run.sh ../librestore_gnu_userconfig

  source:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Package
        run: |
          ./.librestore/source.sh .
          ls ./*.zip # Asserts the file is there

  utouch:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install clickable
        run: |
          # For whatever reason, I have to manually install runc before docker.io or containerd, else it fails because of broken dependency
          # Using apt-get because apt complains it shouldn't be used in scripts
          sudo apt-get update
          sudo apt-get install -y runc
          sudo apt-get install -y docker.io adb git python3 python3-pip
          pip3 install --user git+https://gitlab.com/clickable/clickable.git@debug
          # Clickable requires a reboot/logout. This is a sneaky way to bypass that :^)
          sudo systemctl unmask docker.service
          sudo systemctl start docker.service

      - name: Compile
        run: |
          ./.librestore/utouch.sh .
          ls ./*.click # Asserts the file is there

  wasm:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Compile
        run: |
          ./.librestore/wasm.sh .
          ls index.html supertux2.{data,js,wasm} # Asserts the files are there

  # TODO: Windows
