name: validate
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gnu:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Prepare the environment
        run: |
          sudo apt-get install libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev

      - name: Compile
        run: |
          sudo ./.librestore/gnu.sh /output.zip
          ls /output.zip # Asserts the file is there

  source:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Package
        run: |
          sudo ./.librestore/source.sh /output.zip
          ls /output.zip # Asserts the file is there

  utouch:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install clickable
        run: |
          # For whatever reason, I have to manually install runc before docker.io or containerd, else it fails because of broken dependency
          # Using apt-get because apt complains it shouldn't be used in scripts
          sudo apt-get update
          sudo apt-get install -y runc
          sudo apt-get install -y docker.io adb git python3 python3-pip
          sudo pip3 install git+https://gitlab.com/clickable/clickable.git
          # Clickable requires a reboot/logout. This is a sneaky way to bypass that :^)
          sudo usermod -a -G docker root
          sudo systemctl unmask docker.service
          sudo systemctl start docker.service

      - name: Compile
        run: |
          sudo ./.librestore/utouch.sh /output.zip
          ls /output.zip # Asserts the file is there

  wasm:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Compile
        run: |
          sudo ./.librestore/wasm.sh /output.zip
          ls /output.zip # Asserts the file is there

  # TODO: Windows
